"use strict";

const TASKFACTORY_NAMEID_FINANCEMAIN    = 'finance_main';

const TASK_NAMEID_SSESTOCKLIST          = 'sse_stocklist';
const TASK_NAMEID_SZSESTOCKLIST         = 'szse_stocklist';
const TASK_NAMEID_INITCRAWLERMGR        = 'init_crawlermgr';

exports.TASKFACTORY_NAMEID_FINANCEMAIN  = TASKFACTORY_NAMEID_FINANCEMAIN;

exports.TASK_NAMEID_SSESTOCKLIST        = TASK_NAMEID_SSESTOCKLIST;
exports.TASK_NAMEID_SZSESTOCKLIST       = TASK_NAMEID_SZSESTOCKLIST;
exports.TASK_NAMEID_INITCRAWLERMGR      = TASK_NAMEID_INITCRAWLERMGR;